// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjnearcxlvgtofpjmtdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqbmVhcmN4bHZndG9mcGptdGRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NjEyNTcsImV4cCI6MjA2NTAzNzI1N30.1yfPZcDkZPsAYti-Nro1wSLIAF6C7U9xA7GTKBsY4sU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);